[build]
  base = "frontend"
  publish = "dist"
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  base = "frontend"
  command = "pnpm dev"
  port = 5173
  publish = "dist" 