# Generated by Django 5.2.3 on 2025-07-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="current_cycle_hours",
        ),
    ]
